# Generated by Django 4.0.3 on 2022-04-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appForeground',
            fields=[
                ('field_id', models.AutoField(db_column='_id', primary_key=True, serialize=False)),
                ('timestamp', models.FloatField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, max_length=150, null=True)),
                ('package_name', models.TextField(blank=True, null=True)),
                ('application_name', models.TextField(blank=True, null=True)),
                ('is_system_app', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'applications_foreground',
                'managed': True,
            },
        ),
    ]
