# Generated by Django 4.0.3 on 2022-04-22 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appForeground', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='appForeground',
            new_name='ApplicationsForeground',
        ),
    ]
