# Generated by Django 4.0.3 on 2022-08-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appForeground', '0003_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbLocCluster',
            fields=[
                ('field_id', models.AutoField(db_column='_id', primary_key=True, serialize=False)),
                ('timestamp', models.FloatField(blank=True, null=True)),
                ('device_id', models.CharField(max_length=150)),
                ('double_latitude', models.FloatField(blank=True, null=True)),
                ('double_longitude', models.FloatField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('loc_type', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'tb_loc_cluster',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='SmsSms',
        ),
        migrations.DeleteModel(
            name='TbAdmin',
        ),
        migrations.DeleteModel(
            name='TbClinician',
        ),
    ]
