# Generated by Django 4.0.3 on 2022-05-11 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preProcessLocation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbLocCluster',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.FloatField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, max_length=150, null=True)),
                ('double_latitude', models.FloatField(blank=True, null=True)),
                ('double_longitude', models.FloatField(blank=True, null=True)),
                ('address', models.CharField(blank=True, db_column='address', max_length=255, null=True)),
                ('loc_type', models.CharField(blank=True, db_column='loc_type', max_length=255, null=True)),
            ],
            options={
                'db_table': 'tb_loc_cluster',
                'managed': False,
            },
        ),
    ]
