# Generated by Django 4.0.4 on 2022-04-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_id', models.IntegerField(max_length=11)),
                ('device_id', models.CharField(max_length=150)),
            ],
        ),
    ]
