# Generated by Django 4.0.4 on 2022-04-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='message_type',
            field=models.IntegerField(default=1, max_length=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sms',
            name='sms_id',
            field=models.IntegerField(),
        ),
    ]
