# Generated by Django 4.0.4 on 2022-04-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_sms_message_type_alter_sms_sms_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='timestamp',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sms',
            name='trace',
            field=models.TextField(default=1231),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sms',
            name='message_type',
            field=models.IntegerField(),
        ),
    ]
