# Generated by Django 4.0.3 on 2022-08-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0004_locations_messages_tbclient_delete_sms'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationsForeground',
            fields=[
                ('field_id', models.AutoField(db_column='_id', primary_key=True, serialize=False)),
                ('timestamp', models.FloatField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, max_length=150, null=True)),
                ('package_name', models.TextField(blank=True, null=True)),
                ('application_name', models.TextField(blank=True, null=True)),
                ('is_system_app', models.IntegerField(blank=True, null=True)),
                ('application_category', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'applications_foreground',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254, unique=True)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AwareDevice',
            fields=[
                ('field_id', models.AutoField(db_column='_id', primary_key=True, serialize=False)),
                ('timestamp', models.FloatField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, max_length=150, null=True)),
                ('board', models.TextField(blank=True, null=True)),
                ('brand', models.TextField(blank=True, null=True)),
                ('device', models.TextField(blank=True, null=True)),
                ('build_id', models.TextField(blank=True, null=True)),
                ('hardware', models.TextField(blank=True, null=True)),
                ('manufacturer', models.TextField(blank=True, null=True)),
                ('model', models.TextField(blank=True, null=True)),
                ('product', models.TextField(blank=True, null=True)),
                ('serial', models.TextField(blank=True, null=True)),
                ('release', models.TextField(blank=True, null=True)),
                ('release_type', models.TextField(blank=True, null=True)),
                ('sdk', models.TextField(blank=True, null=True)),
                ('label', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'aware_device',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('field_id', models.AutoField(db_column='_id', primary_key=True, serialize=False)),
                ('timestamp', models.FloatField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, max_length=150, null=True)),
                ('battery_status', models.IntegerField(blank=True, null=True)),
                ('battery_level', models.IntegerField(blank=True, null=True)),
                ('battery_scale', models.IntegerField(blank=True, null=True)),
                ('battery_voltage', models.IntegerField(blank=True, null=True)),
                ('battery_temperature', models.IntegerField(blank=True, null=True)),
                ('battery_adaptor', models.IntegerField(blank=True, null=True)),
                ('battery_health', models.IntegerField(blank=True, null=True)),
                ('battery_technology', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'battery',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BatteryCharges',
            fields=[
                ('field_id', models.AutoField(db_column='_id', primary_key=True, serialize=False)),
                ('timestamp', models.FloatField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, max_length=150, null=True)),
                ('battery_start', models.IntegerField(blank=True, null=True)),
                ('battery_end', models.IntegerField(blank=True, null=True)),
                ('double_end_timestamp', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'battery_charges',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BatteryDischarges',
            fields=[
                ('field_id', models.AutoField(db_column='_id', primary_key=True, serialize=False)),
                ('timestamp', models.FloatField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, max_length=150, null=True)),
                ('battery_start', models.IntegerField(blank=True, null=True)),
                ('battery_end', models.IntegerField(blank=True, null=True)),
                ('double_end_timestamp', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'battery_discharges',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bluetooth',
            fields=[
                ('field_id', models.AutoField(db_column='_id', primary_key=True, serialize=False)),
                ('timestamp', models.FloatField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, max_length=150, null=True)),
                ('bt_address', models.CharField(blank=True, max_length=150, null=True)),
                ('bt_name', models.TextField(blank=True, null=True)),
                ('bt_rssi', models.IntegerField(blank=True, null=True)),
                ('label', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bluetooth',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Calls',
            fields=[
                ('field_id', models.AutoField(db_column='_id', primary_key=True, serialize=False)),
                ('timestamp', models.FloatField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, max_length=150, null=True)),
                ('call_type', models.IntegerField(blank=True, null=True)),
                ('call_duration', models.IntegerField(blank=True, null=True)),
                ('trace', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'calls',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('field_id', models.AutoField(db_column='_id', primary_key=True, serialize=False)),
                ('timestamp', models.FloatField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, max_length=150, null=True)),
                ('screen_status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'screen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbLocCluster',
            fields=[
                ('field_id', models.AutoField(db_column='_id', primary_key=True, serialize=False)),
                ('timestamp', models.FloatField(blank=True, null=True)),
                ('device_id', models.CharField(max_length=150)),
                ('double_latitude', models.FloatField(blank=True, null=True)),
                ('double_longitude', models.FloatField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('loc_type', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'tb_loc_cluster',
                'managed': False,
            },
        ),
    ]
